### ISSUE TITLE
Unable to connect with mysql DB 

### ISSUE THREAD

**Issue by ghost** [RasmusEdgar/kea-centos-srpms#2]
I have installed kea 1.4 based on the rpm spec but after i configured kea not able to start dhcp4 
it show's below error 
"
ERROR [kea-dhcp4.dhcp4/10608] DHCP4_CONFIG_LOAD_FAIL configuration error using file: /etc/kea/kea-dhcp4.conf, reason: Unable to open database: Cannot parse , expected format is name=value
"

Note : 
I have create DB and tables as per the doc and all credentials are correct !

**Comment by RasmusEdgar** [comment]
There seems to be a syntax error in your configuration, without sharing your kea-dhcp4.conf (with passwords redacted of course) I can not help you.

**Comment by ghost** [comment]
Am sorry my mistake, you're exactly right i miss configured the conf file. 
Thanks a lot pointing it out. i guess can i delete this issue post/issue !?

**Comment by RasmusEdgar** [comment]
Good to hear you found the problem. I'll just close this issue. :)
